services:
  - type: web
    name: till-failure-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npm run prisma:deploy && npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4010
